main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('', include('popcorn.urls'), name='MainSite'),
                  path('admin/', admin.site.urls),
                  path('summernote/', include('django_summernote.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

popcorn/urls.py
from django.urls import include, path

from . import views
from .forms import UserRegistrationForm

from django_registration.backends.activation.views import RegistrationView

urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/add/', views.edit_recipe, name='add_recipe'),
    path('recipes/edit/<str:slug>', views.edit_recipe, name='edit_recipe'),
    path('recipes/view/<str:slug>', views.post_comment, name='recipe'),
    path('recipes/view/<str:slug>/vote', views.vote_recipe, name='vote_recipe'), #used on front-end
    path('comments/vote/<int:pk>', views.vote_comment, name='vote_comment'), #used on front-end
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('accounts/profile/', views.index),
    path('accounts/register/',
        RegistrationView.as_view(
            form_class=UserRegistrationForm
        ),
        name='django_registration_register',
    ),
    path('accounts/',
        include('django_registration.backends.activation.urls')
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', views.logout_view, name='logout'),
]

popcorn/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from vote.models import VoteModel
from django.utils import timezone

import datetime
# TODO: Add validators in different areas (images), but research them first
# TODO: Research https://django-simple-history.readthedocs.io for approval history
# TODO: Add convertion of images uploaded by users that are not jpeg's to jpeg's

def validate_recipe_icon(image):
    file_size = image.file.size
    limit_mb = 20
    max_width = 1000
    max_height = 800
    if image.file:
        if image.width > max_width or image.height > max_height:
            raise ValidationError("Max size of file is {} by {}".format(max_width, max_height))
        if file_size > 1024 * 1024 * limit_mb:
            raise ValidationError("Max size of file is {} MB".format(limit_mb))

class User(AbstractUser):
    newsletter_signup = models.BinaryField(blank=True, null=True)
    blocked_on = models.DateTimeField(blank=True, null=True)
    blocked_till = models.DateTimeField(blank=True, null=True)
    blocked_by = models.ForeignKey("User", on_delete=models.SET_NULL, null=True, related_name='blocked_users',
                                   blank=True)
    deleted_on = models.DateTimeField(blank=True, null=True)
    deleted_by = models.ForeignKey("User", on_delete=models.SET_NULL, null=True, related_name='deleted_users',
                                   blank=True)

class Category(models.Model):
    class Tag(models.IntegerChoices):
        PREPARATION_TIME = 1, ('Czasowa') #less than 30 minutes, 30-120 etc.
        MEAL_TIME = 2, ('Pora') #breakfast, dinner etc.
        CUISINE_TYPE = 3, ('Rodzaj') #vegan, normal, vegetarian etc.
        CATEGORY = 4, ('Kategoria') #all other

    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='categories/')
    tag = models.IntegerField(choices=Tag.choices, default=Tag.CATEGORY)

    def __str__(self):
        return self.name

class VoteUtilities():
    ACTIONS = {'up': 0, 'down': 1, 0: 'up', 1: 'down'}
    NONE_ACTION = 'default'

    def get_vote_status(self, user):
        vote = self.votes.get(user.id)
        if vote:
            return self.ACTIONS[vote.action]
        return self.NONE_ACTION

class RecipeManager(models.Manager):

    def get_lastweek(self, amount=3):
        recipes = list(Recipe.objects.filter(created_on__gte=timezone.now() - datetime.timedelta(days=7)).order_by('-vote_score'))
        count = len(recipes)        
        if count == 0:
            return []
        if count < amount:
            for i in range(count, amount):
                recipes.append(recipes[i%count])
        return recipes[:amount]

    def get_best_recipes(self, amount=3):
        recipes = list(Recipe.objects.order_by('-vote_score'))
        count = len(recipes)
        if count == 0:
            return []
        if count < amount:
            for i in range(count, amount):
                recipes.append(recipes[i%count])
        return recipes[:amount]

    def get_proposed(self, amount=3):
        recipes = list(Recipe.objects.order_by('name'))
        count = len(recipes)
        if count == 0:
            return []
        if count < amount:
            for i in range(count, amount):
                recipes.append(recipes[i%count])
        return recipes[:amount]

class Recipe(VoteModel, models.Model, VoteUtilities):
    class Difficulty(models.IntegerChoices):
        VERY_EASY = 1, ('Bardzo łatwa')
        EASY = 2, ('Łatwa')
        NORMAL = 3, ('Średnia')
        DIFFICULT = 4, ('Trudna')
        VERY_DIFFICULT = 5, ('Bardzo trudna')

    id = models.AutoField(primary_key=True)
    slug = models.SlugField(blank=True, null=True)
    name = models.CharField(max_length=120)
    content = models.TextField()
    icon = models.ImageField(upload_to='recipes_icons', validators=[validate_recipe_icon])
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='authored_recipes', blank=True)
    categories = models.ManyToManyField(Category, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    preparation_time = models.PositiveIntegerField()
    servings_count = models.PositiveIntegerField()
    difficulty = models.IntegerField(choices=Difficulty.choices, default=Difficulty.NORMAL, blank=True, null=True)
    hidden_on = models.DateTimeField(null=True, blank=True)
    hidden_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='hidden_recipes',
                                  blank=True)
    deleted_on = models.DateTimeField(null=True, blank=True)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='deleted_recipes',
                                   blank=True)
    objects = RecipeManager()

    def is_hidden(self):
        return self.hidden_on is not None

    def is_deleted(self):
        return self.deleted_on is not None

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.slug = slugify(self.name + " " + str(self.id), allow_unicode=False)
        super().save(*args, **kwargs)

class Comment(VoteModel, models.Model, VoteUtilities):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='authored_comments')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    deleted_on = models.DateTimeField(null=True)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comments_deleted')
    recipe = models.ForeignKey(Recipe, on_delete=models.SET_NULL, null=True, related_name='comments')

    def is_deleted(self):
        return self.deleted_on is not None

class Measurment(models.Model):
    full_name = models.CharField(max_length=120)
    short_name = models.CharField(max_length=6)

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    count = models.PositiveIntegerField()
    measurment = models.ForeignKey(Measurment, on_delete=models.SET_NULL, null=True)

popcorn/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import Recipe, User, Comment, Category
from django_registration.forms import RegistrationForm

# Adding css to django class
# https://stackoverflow.com/questions/5827590/css-styling-in-django-forms
# https://docs.djangoproject.com/en/2.2/topics/forms/#working-with-form-templates
# https://www.youtube.com/watch?v=6-XXvUENY_8

#https://stackoverflow.com/questions/3737116/how-to-add-optgroups-to-a-django-modelmultiplechoicefield

class RecipeForm(forms.ModelForm):
    # name = forms.CharField()
    # difficulty = forms.ChoiceField()
    # recipe = SummernoteTextFormField()

    class Meta:
        model = Recipe
        fields = [
            'name',
            'difficulty',
            'preparation_time',
            'servings_count',
            'categories',
            'icon',
            'content',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'difficulty': forms.Select(attrs={'class': 'form-control'}),
            'preparation_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'servings_count': forms.NumberInput(attrs={'class': 'form-control'}),
            'categories': forms.CheckboxSelectMultiple(choices=["blablabla"]),
            # 'icon': forms.ImageField(),
            'content': SummernoteWidget({
                'summernote': {
                    'width': '100%',
                    'height': '2000',
                },
            }),
        }
        labels = {
            'name': 'Nazwa przepisu',
            'difficulty': 'Trudność',
            'preparation_time': 'Czas przygotowania (w minutach)',
            'servings_count': 'Ilość porcji',
            'categories': 'Kategorie',
            'icon': 'Miniaturka',
            'content': '',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {'content' : SummernoteWidget({
            'summernote': {
                'toolbar': [
                    ['style', ['style', ]],
                    ['font', ['bold', 'italic', 'underline', 'color', ]],
                    ['paragraph', ['paragraph', 'ol', 'ul', ]],
                    ['misc', ['undo', 'redo' ]],
                ],
                'width': '100%',
                'height': '400',
            },
        })}
        labels = {'content': ''}

class UserRegistrationForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = User

popcorn/views.py
import json

from django.conf import settings
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect, reverse
from django.views import generic

from .forms import RecipeForm, CommentForm
from .models import Recipe, Category, Comment

def index(request):
    return render(request, 'popcorn/main_page.html',
    {
        'lastweek': Recipe.objects.get_lastweek(),
        'recipes': Recipe.objects.get_best_recipes(),
        'proposed': Recipe.objects.get_proposed()
    })


def recipe(request, slug):
    return render(request, 'popcorn/recipe.html')


class RecipeView(generic.DetailView):
    model = Recipe
    template_name = 'popcorn/recipe.html'


class CategoriesView(generic.ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'popcorn/categories.html'


def edit_recipe(request, slug=None):
    # TODO: Automatically attach time category
    if not request.user.is_authenticated:
        # Todo add nice page to say that you are not authorized
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    if slug is None:
        recipe = None
    else:
        recipe = get_object_or_404(Recipe, slug=slug)

    if request.method == 'POST':
        form = RecipeForm(request.POST or None, request.FILES or None, instance=recipe)
        if form.is_valid():
            if form.instance.author is None:
                form.instance.author = request.user
            form.save()
            return HttpResponseRedirect(reverse("recipe", kwargs={'slug': form.instance.slug}))
    else:
        form = RecipeForm(request.POST or None, request.FILES or None, instance=recipe)

    return render(request, 'popcorn/recipe_edit.html', {'form': form})


def logout_view(request):
    logout(request)
    return render(request, 'popcorn/logout_success.html')


def vote_recipe(request, slug):
    recipe = Recipe.objects.get(slug=slug)
    user = request.user

    if not user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    vote = recipe.votes.get(user.id)
    body = json.loads(request.body)
    action_string = body['action']
    action_result = action_string
    action_value = recipe.ACTIONS[action_string]

    if vote is not None and vote.action == action_value:
        action_result = recipe.NONE_ACTION
        recipe.votes.delete(user.id)
    else:
        recipe.votes.vote(user.id, action_value)

    recipe = Recipe.objects.get(slug=slug)
    return JsonResponse({'action': action_result, 'count': recipe.vote_score})


def vote_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    user = request.user

    if not user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    vote = comment.votes.get(user.id)
    body = json.loads(request.body)
    action_string = body['action']
    action_result = action_string
    action_value = comment.ACTIONS[action_string]

    if vote is not None and vote.action == action_value:
        action_result = comment.NONE_ACTION
        comment.votes.delete(user.id)
    else:
        comment.votes.vote(user.id, action_value)

    comment = Comment.objects.get(pk=pk)
    return JsonResponse({'action': action_result, 'count': comment.vote_score})


def post_comment(request, slug):
    template_name = 'popcorn/recipe.html'
    recipe = get_object_or_404(Recipe, slug=slug)
    # Todo add check for deleted comments
    # comments = recipe.comments.filter(active=True)
    comments = recipe.comments.all()
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        if not request.user.is_authenticated:
            # Todo add nice page to say that you are not authorized
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.recipe = recipe
            if new_comment.author is None:
                new_comment.author = request.user
            # Save the comment to the database
            new_comment.save()
            # Add upvote for the comment from the creater.
            new_comment.votes.vote(request.user.id, new_comment.ACTIONS['up'])
            return HttpResponseRedirect(reverse("recipe", kwargs={'slug': slug}))
    else:
        if not request.user.is_authenticated:
            comment_form = None
        else:
            comment_form = CommentForm()

    comments = zip(
        comments,
        [c.get_vote_status(request.user) for c in comments]
    )

    return render(request, template_name, {'recipe': recipe,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'vote_status': recipe.get_vote_status(request.user)})

popcorn/templates/popcorn/base.html
{% load static %}
<html>
<head>
    <title>{% block title %}Popcorn{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'popcorn/css/style.css' %}">
    {% block additional_js %}
    {% endblock additional_js %}
</head>
<body class="bg">
<nav class="navbar navbar-expand-lg navbar-light navbar-cstm">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'popcorn/images/brand.png' %}" height="60">
    </a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto h5  align-items-center">
            <li class="nav-item px-2">
                <a class="nav-link" href="{% url 'categories' %}">Kategorie</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'add_recipe' %}">Dodaj Przepis</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link">Zalogowano jako {{ user.username }}</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'logout' %}">Wyloguj</a>
                </li>
            {% else %}
                <li class="nav-item active px-2">
                    <a class="nav-link" href="{% url 'login' %}">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-square"
                             fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                            <path fill-rule="evenodd"
                                  d="M2 15v-1c0-1 1-4 6-4s6 3 6 4v1H2zm6-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div
    >
</nav>

<main role="main" class="content container d-flex flex-column min-vh-100">
    {% block content %}
    {% endblock %}
</main>

<footer class="footer mt-auto py-3 navbar-cstm ">
    <div class="container">
        <div class="row align-items-top">
            <div class="col py-2">
                <h2 >NEWSLETTER</h1>
                <label for="inputEmailNewsletter" class="sr-only">Adres Email Newsletter</label>
                <input type="email" id="inputEmailNewsletter" class="form-control inputBox cstm-shadow"
                       placeholder="Adres Email" required>
                <button class="btn classic-btn cstm-shadow btn-lg top-buffer align-self-end" type="submit">Zapisz się
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-right-fill"
                         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path
                                d="M12.14 8.753l-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                    </svg>
                </button>

            </div>
            <div class="col py-2 d-flex flex-column">
                <span class="text-muted">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</span>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

popcorn/templates/popcorn/categories.html
{% extends "popcorn/base.html" %}
{% block title %}Kategorie{% endblock %}

{% block content %}
    <ul>
        {% for c in categories %}
            <li>
{#                <a href=" {% url 'c' c.slug %}">{{ r.name }}</a> #}
                <a>{{ c.name }} : {{ c.get_tag_display }}</a>
                <br>
                {% if c.image %}
                    <img src="{{ c.image.url }}" style="width: 500px">
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

popcorn/templates/popcorn/logout_success.html
{% extends "popcorn/base.html" %}
{% block title %}Strona główna{% endblock %}

{% block content %}
    <h1 class="display-2 top-buffer align-self-center">Wylogowano Pomyślnie</h1>
    
{% endblock %}

popcorn/templates/popcorn/recipe.html
{% extends "popcorn/base.html" %}
{% load static %}
{% block title %}
    {{ recipe.name }}
{% endblock %}
{% block additional_js %}
    <script src="{% static 'popcorn/js/recipe.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="card margin-big ">
        <div class="card-body">
            <div class="col">
                <div class="col">
                    <div class="text-right">
                        <a class="btn classic-btn" href=" {% url 'edit_recipe' recipe.slug %}">Edytuj</a>
                    </div>
                </div>
                <h2 class="card-title text-center">{{ recipe.name }}</h2>
                {% if recipe.author %}
                    <h4 class="text-center">Autor: {{ recipe.author }}</h4>
                {% else %}
                    <h4 class="text-center">Autor: Brak</h4>
                {% endif %}
                <h4 class="text-center">Czas wykonania: {{ recipe.preparation_time }} min</h4>
                <h4 class="text-center">Ilość porcji: {{ recipe.servings_count }}</h4>
                <h4 class="text-center">Trudność wykonania: {{ recipe.get_difficulty_display }}</h4>
                <!--TODO: Add scaling-->
                {% if recipe.icon %}
                <div class="span3 top1">  
                    <div class="row">
                        <div class="span3 food1">
                            <img  src="{{ recipe.icon.url }}" class="image-responsive">
                        </div>
                    </div>
                </div>
                {% endif %}

                <!--TODO: Add ingredients -->
                <!--TODO: Add categories -->
                <!--TODO: Add voting-->
                {% if user.is_authenticated %}
                    {% if vote_status == 'up' %}
                        <a class="nav-link vote vote-up" id="recipe-vote-button-up">Like</a>
                        <a class="nav-link vote" id="recipe-vote-button-down">Unlike</a>
                    {% elif vote_status == 'down' %}
                        <a class="nav-link vote" id="recipe-vote-button-up">Like</a>
                        <a class="nav-link vote vote-down" id="recipe-vote-button-down">Unlike</a>
                    {% else %}
                        <a class="nav-link vote" id="recipe-vote-button-up">Like</a>
                        <a class="nav-link vote" id="recipe-vote-button-down">Unlike</a>
                    {% endif %}
                {% else %}
                    <h4>Chcesz głosować? <a href="{% url 'login' %}">Zaloguj się!</a></h4>
                {% endif %}
                <h4 class="text-center" id="recipe-vote-count">Głosy: {{ recipe.vote_score }}</h4>
                <h4 class="text-center"></h4>
                <!--TODO: Add food icon-->
                {{ recipe.content|safe }}
                <br></br>

                {% if user.is_authenticated %}
                    <form method="post" style="margin-top: 1.3em;">
                        {{ comment_form.as_p }}
                        {% csrf_token %}

                            <div class="col">
                                <div class="text-right">
                                    <button type="submit" class="btn classic-btn cstm-shadow btn-lg btn-block">Odpowiedz</button>
                                </div>
                            </div>

                    </form>
                {% else %}
                    <p>Zaloguj się aby mieć możliwość dodawania komentarzy.</p>
                {% endif %}

                <!--TODO: Add comments-->
                <ol>
                    {% for c, status in comments %}
                        {% if c.author %}
                            <a><strong>Autor:</strong> {{ c.author }} </a>
                        {% else %}
                            <a><strong>Autor:</strong> [Skasowany] </a>
                        {% endif %}
                        <div class="text" id="comment-vote-count-{{ c.id }}">Głosy: {{ c.vote_score }}</div>
                        {% if user.is_authenticated %}
                            {% if status == 'up' %}
                                <a class="nav-link vote vote-up" id="comment-vote-button-up-{{ c.id }}">Like</a>
                                <a class="nav-link vote" id="comment-vote-button-down-{{ c.id }}">Unlike</a>
                            {% elif status == 'down' %}
                                <a class="nav-link vote" id="comment-vote-button-up-{{ c.id }}">Like</a>
                                <a class="nav-link vote vote-down" id="comment-vote-button-down-{{ c.id }}">Unlike</a>
                            {% else %}
                                <a class="nav-link vote" id="comment-vote-button-up-{{ c.id }}">Like</a>
                                <a class="nav-link vote" id="comment-vote-button-down-{{ c.id }}">Unlike</a>
                            {% endif %}
                        {% endif %}
                        <br>
                        <a>{{ c.content|safe }} </a>
                        <hr>
                    {% endfor %}
                </ol>
                
            </div>
        </div>
    </div>
{% endblock %}

popcorn/templates/popcorn/recipe_edit.html
{% extends "popcorn/base.html" %}
{% block title %}Dodaj nowy przepis{% endblock %}

{% block content %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn classic-btn cstm-shadow btn-lg btn-block" type="submit" value="Zapisz">Przeslij przepis!</button>
    </form>
    
{% endblock %}